DROP TABLE IF EXISTS "WAREHOUSESCHEDULE";
DROP TABLE IF EXISTS "WAREHOUSE";
DROP TABLE IF EXISTS "FLOORNUMBER";
DROP TABLE IF EXISTS "EMPLOYEE";
DROP TABLE IF EXISTS "DRIVES";
DROP TABLE IF EXISTS "COMPANYVAN";

DROP VIEW IF EXISTS carsForRetirement;
DROP VIEW IF EXISTS employeesByDepartment;
DROP VIEW IF EXISTS freedUpCoordinates;